trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureWebAppName: 'github-stargazers-webapi'
  webApiProject: 'src/backend/GitHubStargazers.WebApi/*.csproj'
  testProject: 'src/backend/GitHubStargazers.Tests/*.csproj'

stages:
- stage: BuildAndTest
  displayName: 'Build, Test and Publish'
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      displayName: 'Installa .NET 10 SDK'
      inputs:
        packageType: 'sdk'
        version: '10.x'

    # Tests
    - task: DotNetCoreCLI@2
      displayName: 'Execute XUnit Tests'
      inputs:
        command: 'test'
        projects: '$(testProject)'
        arguments: '--configuration $(buildConfiguration)'

    # Publish WebApi
    - task: DotNetCoreCLI@2
      displayName: 'Compile And Publish WebApi'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(webApiProject)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    # Save artifact
    - task: PublishBuildArtifacts@1
      displayName: 'Save Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

# deploy to Azure if tests pass
- stage: Deploy
  displayName: 'Azure Deploy Fase'
  dependsOn: BuildAndTest
  condition: succeeded()
  jobs:
  - job: DeployJob
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(4057d1da-e109-4ad4-8f44-43cbfbf20647)'
        appType: 'webAppLinux'
        WebAppName: 'github-stargazers-webapi'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        RuntimeStack: 'DOTNETCORE|10.0'
        DeploymentTypeLinux: 'oneDeploy'