trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/ai/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'githubstargazersregistry'
  resourceGroup: 'github-stargazers'
  serviceConnection: 'Azure subscription 1(4057d1da-e109-4ad4-8f44-43cbfbf20647)'

stages:
- stage: BuildAndPush
  displayName: 'Build e Push Images'
  jobs:
  - job: BuildImages
    steps:
    - task: AzureCLI@2
      displayName: 'Build e Push Docker Containers'
      inputs:
        azureSubscription: '$(serviceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(acrName)
          
          # 2. Build & Push Ollam
          echo "Compiling Ollama..."
          docker build -t $(acrName).azurecr.io/ollama-ai:latest -f src/ai/ollama/Dockerfile src/ai/ollama
          docker push $(acrName).azurecr.io/ollama-ai:latest
          
          # 3. Build & Push Qdrant
          echo "Compiling di Qdrant..."
          docker build -t $(acrName).azurecr.io/qdrant-db:latest -f src/ai/qdrant/Dockerfile src/ai/qdrant
          docker push $(acrName).azurecr.io/qdrant-db:latest